DEVICE          : cpu             # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)

SAVE_DIR        : 'save_dir'         # output folder name used for saving the model, logs and inference results

MODEL:
  NAME          : BiSeNetv1Disp3                                          # name of the model you are using
  BACKBONE      : MicroNet-M1                                                # model variant
  PRETRAINED    : #'checkpoints/micronet-m1.pth'              # backbone model's weight
  WEIGHTS       : 'BiSeNetv1Disp2_MicroNet-M1_HumanCOCO.pth'

DATASET:
  NAME          : HumanReal                                            # dataset name

  ROOT          : '/Users/rithik/Desktop/bsdr/scripts/april_6_capture_frames'                         # dataset root path
  IGNORE_LABEL  : 255
  CALIB         : '/panavision/datasets/Thesis/jan_23_capture/calibration/sr_calibration.json'
  TEST_BAG      : '/panavision/datasets/Thesis/jan_23_capture/bags/jan_23_15.bag'
  GT_RIGHT_ALIGN: true
  EXR_DISP      : false
  LOAD_FILTERED : false
  FILTER_CLOSE  : false
  MEDIAN_FILTER : false
  NORM_DISP     : true
  NORM_GT_DISP  : false
  MAX_DISP      : 256
  NORM_IMG      : true

TRAIN:
  IMAGE_SIZE    : [384, 640]    # training image size in (h, w)
  BATCH_SIZE    : 10              # batch size used to train
  MOSAIC        : false
  EPOCHS        : 1
               # number of epochs to train
  EVAL_INTERVAL : 20              # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : false           # use DDP training
  FREEZE_SEG    : false
  SPECIAL_LOAD  : true

LOSS:
  NAME          : SeparationDispLoss          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : true            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.001            # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.0001          # decay rate used in optimizer

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio

EVAL:
  MODEL_PATH    : '/Users/rithik/Desktop/bsdr/scripts/save_dir/BiSeNetv1Disp3_MicroNet-M1_HumanReal.pth'  # trained model file path
  IMAGE_SIZE    : [384, 640]                        # evaluation image size in (h, w)
  MSF:
    ENABLE      : false                               # multi-scale and flip evaluation
    FLIP        : true                                # use flip in evaluation
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]   # scales used in MSF evaluation

TEST:
  # MODEL_PATH    : 'runs/coco_best/BiSeNetv1Disp2_MicroNet-M1_HumanCOCO.pth'  # trained model file path
  MODEL_PATH    : '/Users/rithik/Desktop/bsdr/scripts/save_dir/last.pth'  # trained model file path
  FILE          : '/Users/rithik/Desktop/bsdr/scripts/test_image/april_6_1_rect_right_52.png'                                                   # filename or foldername
  IMAGE_SIZE    : [384, 640]                                                           # inference image size in (h, w)
  OVERLAY       : true